# Generated by Django 5.1.4 on 2026-03-18 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_orderitem_product_price_alter_orderitem_order'),
        ('home', '0004_alter_shippingaddress_area_sector_locality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
