# Generated by Django 5.1.4 on 2026-03-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_add_sneaker_data_to_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='for_new_users',
            field=models.BooleanField(default=False),
        ),
    ]
