# Generated by Django

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='flat_house_building_name',
            field=models.CharField(default='', max_length=200, verbose_name='Flat/House/Building name'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='area_sector_locality',
            field=models.CharField(default='', max_length=100, verbose_name='Area / Sector / Locality'),
        ),
    ]

