# Generated by Django 5.1.4 on 2026-03-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_add_shippingaddress_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='area_sector_locality',
            field=models.CharField(max_length=100, verbose_name='Area / Sector / Locality'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='flat_house_building_name',
            field=models.CharField(max_length=200, verbose_name='Flat/House/Building name'),
        ),
    ]
